#KNN_sklearn



In [1]:
import pandas as pd

In [21]:
data = pd.read_csv("iris.csv", names=["s1","sw","pl","pw","class"])

data.head()

,s1,sw,pl,pw,class
0,5.1,3.5,1.4,0.2,Iris-setosa
1,4.9,3.0,1.4,0.2,Iris-setosa
2,4.7,3.2,1.3,0.2,Iris-setosa
3,4.6,3.1,1.5,0.2,Iris-setosa
4,5.0,3.6,1.4,0.2,Iris-setosa


In [22]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split

K-En Yakın Komşu (KNN) sınıflandırıcısıdır. Yeni bir örneğin etiketini, eğitim verisindeki en yakın k komşusuna bakarak tahmin eder (ör. k=5).

In [23]:
Y=data.pop("class")
X=data

In [27]:
train_x, test_x, train_y, test_y =train_test_split(X,Y,test_size=0.2)

In [25]:
from sklearn.preprocessing import StandardScaler

In [28]:
mms=StandardScaler()
mms.fit(train_x)
train_x=mms.transform(train_x)
test_x=mms.transform(test_x)

#eğitim verisini dönüştürüyor

In [29]:
knn_model=KNeighborsClassifier(n_neighbors=3)
knn_model.fit(train_x,train_y)

KNeighborsClassifier(n_neighbors=3)

In [30]:
knn_model.predict([[6.3,2.5,5.0,1.9]])

array(['Iris-virginica'], dtype=object)

In [31]:
len(test_x)

30

In [36]:
predicted_y=knn_model.predict(test_x)
predicted_y

array(['Iris-versicolor', 'Iris-virginica', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-versicolor', 'Iris-virginica',
       'Iris-virginica', 'Iris-versicolor', 'Iris-virginica',
       'Iris-setosa', 'Iris-virginica', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-setosa', 'Iris-versicolor', 'Iris-setosa', 'Iris-versicolor',
       'Iris-virginica', 'Iris-virginica', 'Iris-setosa', 'Iris-setosa'],
      dtype=object)

In [38]:
for i in predicted_y:
  pass
true_counter=0
index_counter=0
for prediction,real in zip(predicted_y,test_y):
  if prediction==real:
    true_counter+=1
  else:
    print(prediction,real,index_counter)
    index_counter+=1

Iris-versicolor Iris-virginica 0
Iris-virginica Iris-versicolor 1


In [39]:
total_test_samples=len(test_y)
oran=round((true_counter/total_test_samples)*100,2)
print("Oran:%",oran)

Oran:% 93.33


#Knn


In [40]:
import pandas as d

In [42]:
data = pd.read_csv("iris.csv", names=["sl","sw","pl","pw","class"])
data.head()

,sl,sw,pl,pw,class
0,5.1,3.5,1.4,0.2,Iris-setosa
1,4.9,3.0,1.4,0.2,Iris-setosa
2,4.7,3.2,1.3,0.2,Iris-setosa
3,4.6,3.1,1.5,0.2,Iris-setosa
4,5.0,3.6,1.4,0.2,Iris-setosa


In [43]:
sample_1 = [4.8,3.0,1.4,0.1] # setosa
sample_2 = [6.4,2.9,4.3,1.3] # versicolor
sample_3 = [6.3,2.5,5.0,1.9] # virgina

K = 3

In [44]:
def calculate_distance(ins1,ins2):
  sum=0
  for index in range(len(ins1)):
    sum+=(ins1[index]-ins2[index])**2
  sqr=sum**0.5
  return sqr

In [45]:
#test distance function
sample_a = [1,1,2,3,5]
sample_b = [2,2,2,3,4]
calculate_distance(sample_a,sample_b)

1.7320508075688772

In [47]:
print("Sınıflandırma : ",sample_2 )
distance_list=[]
for index,row in data.iterrows():
  data_sample=row.values[:-1]
  true_class=row.values[-1]
  distance=calculate_distance(data_sample,sample_2)
  print(data_sample,true_class,distance)
  distance_list.append([distance,true_class,distance])


Sınıflandırma :  [6.4, 2.9, 4.3, 1.3]
[5.1 3.5 1.4 0.2] Iris-setosa 3.416138170507745
[4.9 3.0 1.4 0.2] Iris-setosa 3.4467375879228173
[4.7 3.2 1.3 0.2] Iris-setosa 3.6318039594669758
[4.6 3.1 1.5 0.2] Iris-setosa 3.511409973215888
[5.0 3.6 1.4 0.2] Iris-setosa 3.474190553208042
[5.4 3.9 1.7 0.4] Iris-setosa 3.0935416596516037
[4.6 3.4 1.4 0.3] Iris-setosa 3.5916569992135945
[5.0 3.4 1.5 0.2] Iris-setosa 3.3555923471125038
[4.4 2.9 1.4 0.2] Iris-setosa 3.6905284174491872
[4.9 3.1 1.5 0.1] Iris-setosa 3.4014702703389896
[5.4 3.7 1.5 0.2] Iris-setosa 3.269556544854363
[4.8 3.4 1.6 0.2] Iris-setosa 3.3630343441600474
[4.3 3.0 1.1 0.1] Iris-setosa 4.012480529547776
[5.8 4.0 1.2 0.2] Iris-setosa 3.5199431813596083
[5.7 4.4 1.5 0.4] Iris-setosa 3.374907406137241
[5.4 3.9 1.3 0.4] Iris-setosa 3.4365680554879168
[5.1 3.5 1.4 0.3] Iris-setosa 3.385262175962152
[5.7 3.8 1.7 0.3] Iris-setosa 3.009983388658482
[5.1 3.8 1.5 0.3] Iris-setosa 3.3674916480965473
[5.4 3.4 1.7 0.2] Iris-setosa 3.0364452

In [49]:
distance_list

[[3.416138170507745, 'Iris-setosa', 3.416138170507745],
 [3.4467375879228173, 'Iris-setosa', 3.4467375879228173],
 [3.6318039594669758, 'Iris-setosa', 3.6318039594669758],
 [3.511409973215888, 'Iris-setosa', 3.511409973215888],
 [3.474190553208042, 'Iris-setosa', 3.474190553208042],
 [3.0935416596516037, 'Iris-setosa', 3.0935416596516037],
 [3.5916569992135945, 'Iris-setosa', 3.5916569992135945],
 [3.3555923471125038, 'Iris-setosa', 3.3555923471125038],
 [3.6905284174491872, 'Iris-setosa', 3.6905284174491872],
 [3.4014702703389896, 'Iris-setosa', 3.4014702703389896],
 [3.269556544854363, 'Iris-setosa', 3.269556544854363],
 [3.3630343441600474, 'Iris-setosa', 3.3630343441600474],
 [4.012480529547776, 'Iris-setosa', 4.012480529547776],
 [3.5199431813596083, 'Iris-setosa', 3.5199431813596083],
 [3.374907406137241, 'Iris-setosa', 3.374907406137241],
 [3.4365680554879168, 'Iris-setosa', 3.4365680554879168],
 [3.385262175962152, 'Iris-setosa', 3.385262175962152],
 [3.009983388658482, 'Iris-s

In [50]:
sorted_distance_list=sorted(distance_list,key=lambda x:x[1])
print(sorted_distance_list)

[[3.416138170507745, 'Iris-setosa', 3.416138170507745], [3.4467375879228173, 'Iris-setosa', 3.4467375879228173], [3.6318039594669758, 'Iris-setosa', 3.6318039594669758], [3.511409973215888, 'Iris-setosa', 3.511409973215888], [3.474190553208042, 'Iris-setosa', 3.474190553208042], [3.0935416596516037, 'Iris-setosa', 3.0935416596516037], [3.5916569992135945, 'Iris-setosa', 3.5916569992135945], [3.3555923471125038, 'Iris-setosa', 3.3555923471125038], [3.6905284174491872, 'Iris-setosa', 3.6905284174491872], [3.4014702703389896, 'Iris-setosa', 3.4014702703389896], [3.269556544854363, 'Iris-setosa', 3.269556544854363], [3.3630343441600474, 'Iris-setosa', 3.3630343441600474], [4.012480529547776, 'Iris-setosa', 4.012480529547776], [3.5199431813596083, 'Iris-setosa', 3.5199431813596083], [3.374907406137241, 'Iris-setosa', 3.374907406137241], [3.4365680554879168, 'Iris-setosa', 3.4365680554879168], [3.385262175962152, 'Iris-setosa', 3.385262175962152], [3.009983388658482, 'Iris-setosa', 3.0099833

In [51]:
sorted_distance_list[:3]

[[3.416138170507745, 'Iris-setosa', 3.416138170507745],
 [3.4467375879228173, 'Iris-setosa', 3.4467375879228173],
 [3.6318039594669758, 'Iris-setosa', 3.6318039594669758]]

In [53]:
class_list = []
for i in range(3):
    class_info = sorted_distance_list[i][0]
    class_list.append(class_info)

In [54]:
[i[0] for i in sorted_distance_list]

[3.416138170507745,
 3.4467375879228173,
 3.6318039594669758,
 3.511409973215888,
 3.474190553208042,
 3.0935416596516037,
 3.5916569992135945,
 3.3555923471125038,
 3.6905284174491872,
 3.4014702703389896,
 3.269556544854363,
 3.3630343441600474,
 4.012480529547776,
 3.5199431813596083,
 3.374907406137241,
 3.4365680554879168,
 3.385262175962152,
 3.009983388658482,
 3.3674916480965473,
 3.036445290137795,
 3.3136083051561784,
 3.9786932528155523,
 3.0413812651491097,
 3.1272991542223783,
 3.2357379374726873,
 3.2109188716004646,
 3.2939338184001206,
 3.363034344160048,
 3.388214869219483,
 3.3316662497915366,
 3.146426544510455,
 3.4871191548325386,
 3.4813790371058424,
 3.4014702703389896,
 3.5874782229304194,
 3.3734255586866007,
 3.4014702703389896,
 3.7709415269929605,
 3.3151168908501556,
 3.509985754956849,
 3.737646318206152,
 3.7815340802378077,
 3.1780497164141406,
 3.01164406927512,
 3.4612136599753565,
 3.3166247903554,
 3.598610843089317,
 3.301514803843836,
 3.4263683398

In [55]:
predicted_class = pd.Series(class_list).value_counts().idxmax()
predicted_class

np.float64(3.416138170507745)